version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /toolset/
    schedule:
      interval: weekly
