# Dependabot. The application allows automating dependencies updates.
# It provides information to Dependabot about used package ecosystems.
#
# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates.
version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      time: '06:00'
      timezone: UTC
    labels:
      - 'type: improvement'
      - 'scope: code'
      - 'scope: deps'
    commit-message:
      prefix: 'feat'
      include: 'scope'

  - package-ecosystem: gomod
    directory: /toolset/
    schedule:
      interval: daily
      time: '06:00'
      timezone: UTC
    labels:
      - 'type: improvement'
      - 'scope: inventory'
      - 'scope: deps'
    commit-message:
      prefix: 'tools'
      include: 'scope'
    open-pull-requests-limit: 10
