repository:
  has_wiki: false
  has_issues: true
  has_projects: false

  allow_forking: false

  allow_merge_commit: true
  allow_squash_merge: true
  use_squash_pr_title_as_default: true
  allow_rebase_merge: true
  allow_update_branch: false
  allow_auto_merge: false
  delete_branch_on_merge: true

  default_branch: main

  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true

branches:
  - name: main
    protection:
      required_linear_history: true
