#!/usr/bin/env bash

set -o nounset
set -o pipefail

root="${HOME}"/.dotfiles

if ! command -v git >/dev/null; then
  echo Git not found
  exit 1
fi

if ! command -v ruby >/dev/null; then
  echo Ruby not found
  exit 1
fi

if ! command -v curl >/dev/null; then
  echo cURL not found
  exit 1
fi

if [ ! -d "${root}" ]; then
  echo Installing dotfiles...
  mkdir -p "${root}"
  git clone git@github.com:kamilsk/dotfiles.git "${root}"

  if command -v bash >/dev/null; then
    echo Integrating with Bash...
    echo "source '${root}'/.profile" >>"${HOME}"/.bash_profile
    echo "source '${root}'/.bash_profile" >>"${HOME}"/.bash_profile
  fi

  if command -v zsh >/dev/null; then
    echo Integration with Zsh...
    echo "source '${root}'/.profile" >>"${HOME}"/.zshrc
    echo "source '${root}'/.zshrc" >>"${HOME}"/.zshrc
  fi
fi

if ! command -v brew >/dev/null; then
  echo Installing Homebrew...
  ruby -e "$(curl -sSfL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo Installing Homebrew bundle...
brew update
brew bundle --file="${root}"/toolset/Brewfile --no-upgrade
