#!/usr/bin/env bash

set -o xtrace
set -o errexit
set -o nounset
set -o pipefail

if ! [ -d "${HOME}"/.dotfiles ]; then git clone git@github.com:kamilsk/shared.git "${HOME}"/.dotfiles; fi

cd "${HOME}"/.dotfiles && git reset --hard && git clean -df && git checkout dotfiles && git pull

if [ -f "${HOME}"/.zshrc ]; then
    `which zsh` -c "source ${HOME}/.zshrc";
elif [ -f "${HOME}"/.bash_profile ]; then
    `which bash` -c "source ${HOME}/.bash_profile";
fi
