#!/usr/bin/env bash

set -o xtrace
set -o errexit
set -o nounset
set -o pipefail

if [ "$(pwd)" != "${HOME}"/.dotfiles ]; then
    if ! [ -d "${HOME}"/.dotfiles ]; then
        git clone git@github.com:kamilsk/shared.git "${HOME}"/.dotfiles;
    fi
    (
        cd "${HOME}"/.dotfiles \
        && git reset --hard \
        && git clean -df \
        && git checkout dotfiles \
        && git pull
    )
fi

exec $SHELL -l
