#!/usr/bin/env bash

set -euo pipefail

# maybe in the future
#    1569813296 # 1Password for Safari
#    411643860  # DaisyDisk
#    803453959  # Slack
#    747648890  # Telegram
#    966085870  # TickTick

function install() {
  local list=(
    1356178125 # Outline-Secure internet access
  )

  for app in "${list[@]}"; do
    if ! mas list | awk '{print $1}' | grep "^${app}$" >/dev/null; then
      mas install "${app}"
    fi
  done
}

function __default() {
  mas list
}

"${@:-__default}"
