// Code generated by github.com/kamilsk/egg. DO NOT EDIT.

// +build tools

package tools

import (
	_ "github.com/adonovan/spaghetti"
	_ "github.com/cube2222/octosql"
	_ "github.com/ericchiang/pup"
	_ "github.com/evanw/esbuild/cmd/esbuild"
	_ "github.com/golang/mock/mockgen"
	_ "github.com/isacikgoz/gia"
	_ "github.com/itchyny/gojq/cmd/gojq"
	_ "github.com/junegunn/fzf"
	_ "github.com/kyoh86/git-vertag"
	_ "github.com/mikefarah/yq/v4"
	_ "github.com/mrnugget/fzz"
	_ "github.com/multiprocessio/dsq"
	_ "golang.org/x/exp/cmd/gorelease"
	_ "mvdan.cc/gofumpt"
	_ "npf.io/gorram"
)

//go:generate go install github.com/adonovan/spaghetti
//go:generate go install github.com/cube2222/octosql
//go:generate go install github.com/ericchiang/pup
//go:generate go install github.com/evanw/esbuild/cmd/esbuild
//go:generate go install github.com/golang/mock/mockgen
//go:generate go install github.com/isacikgoz/gia
//go:generate go install github.com/itchyny/gojq/cmd/gojq
//go:generate go install github.com/junegunn/fzf
//go:generate go install github.com/kyoh86/git-vertag
//go:generate go install github.com/mikefarah/yq/v4
//go:generate go install github.com/mrnugget/fzz
//go:generate go install github.com/multiprocessio/dsq
//go:generate go install golang.org/x/exp/cmd/gorelease
//go:generate go install mvdan.cc/gofumpt
//go:generate go install npf.io/gorram
