// Code generated by github.com/kamilsk/egg. DO NOT EDIT.

// +build tools

package tools

import (
	_ "github.com/cube2222/octosql/cmd/octosql"
	_ "github.com/ericchiang/pup"
	_ "github.com/evanw/esbuild/cmd/esbuild"
	_ "github.com/golang/mock/mockgen"
	_ "github.com/goreleaser/godownloader"
	_ "github.com/isacikgoz/gia"
	_ "github.com/junegunn/fzf"
	_ "github.com/kyoh86/looppointer/cmd/looppointer"
	_ "github.com/mrnugget/fzz"
	_ "golang.org/x/exp/cmd/gorelease"
	_ "mvdan.cc/gofumpt"
)

//go:generate go install github.com/cube2222/octosql/cmd/octosql
//go:generate go install github.com/ericchiang/pup
//go:generate go install github.com/evanw/esbuild/cmd/esbuild
//go:generate go install github.com/golang/mock/mockgen
//go:generate go install github.com/goreleaser/godownloader
//go:generate go install github.com/isacikgoz/gia
//go:generate go install github.com/junegunn/fzf
//go:generate go install github.com/kyoh86/looppointer/cmd/looppointer
//go:generate go install github.com/mrnugget/fzz
//go:generate go install golang.org/x/exp/cmd/gorelease
//go:generate go install mvdan.cc/gofumpt
