# brew bundle --file=OctoMac-mini.Brewfile -v
# brew bundle cleanup --file=OctoMac-mini.Brewfile --force -v

brew "bash"
brew "curl"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "ffmpeg"
brew "git"
brew "git-lfs"
brew "gh"
brew "go"
brew "mas"
brew "node"
brew "ollama"
brew "php"
brew "python"
brew "ruby"
brew "rust"
brew "telnet"
brew "tree"
brew "wget"
brew "yt-dlp"
brew "zsh"
brew "zsh-completions"

tap "buo/cask-upgrade"
brew "octolab/tap/maintainer"
brew "octolab/tap/sparkle"

cask "1password"
cask "1password-cli"
cask "amneziavpn"
cask "arc"
cask "chatbox"
cask "chatgpt"
cask "claude"
cask "claude-code"
cask "cleanmymac"
cask "cleanshot"
cask "codex"
cask "codex-app"
cask "docker-desktop"
cask "gpg-suite"
cask "jan"
cask "jordanbaird-ice"
cask "lm-studio"
cask "macwhisper"
cask "marta"
cask "obsidian"
cask "ollama-app"
cask "outline-manager"
cask "raycast"
cask "sublime-merge"
cask "sublime-text"
cask "warp"
cask "zed"
