# brew list --formula | cat | pbcopy
# open https://formulae.brew.sh/formula/<id>
# brew bundle --file=OctoMac-Pro.Brewfile -v
# brew bundle cleanup --file=OctoMac-Pro.Brewfile --force -v

brew "actionlint"
brew "ansible"
brew "bash"
brew "cue"
brew "curl"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "ffmpeg"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "go"
brew "golangci-lint"
brew "goreleaser"
brew "grpcurl"
brew "jq"
brew "kubectx"
brew "kubernetes-cli"
brew "mas"
brew "node"
brew "ollama"
brew "php"
brew "python"
brew "ruby"
brew "rust"
brew "telnet"
brew "tree"
brew "wget"
brew "yt-dlp"
brew "zsh"
brew "zsh-completions"

cask "1password"
cask "1password-cli"
cask "amneziavpn"
cask "arc"
cask "chatbox"
cask "chatgpt"
cask "claude"
cask "claude-code@latest" # temporary until https://github.com/anthropics/claude-code/issues/63456
cask "cleanmymac"
cask "cleanshot"
cask "codex"
cask "docker-desktop"
cask "google-chrome"
cask "gpg-suite"
cask "jetbrains-toolbox"
cask "jordanbaird-ice"
cask "logseq"
cask "macwhisper"
cask "marta"
cask "obsidian"
cask "ollama-app"
cask "outline-manager"
cask "raycast"
cask "sublime-merge"
cask "sublime-text"
cask "tolaria"
cask "warp"
cask "yandex"
cask "zed"

tap "buo/cask-upgrade", trusted: true
cask "docker/tap/sbx", trusted: true
cask "octolab/tap/indexit", trusted: true
# brew "octolab/tap/maintainer", trusted: true # temporary disable for local dev
brew "octolab/tap/sparkle", trusted: true
cask "steipete/tap/codexbar", trusted: true, args: { adopt: true }
