// Code generated by github.com/kamilsk/egg. DO NOT EDIT.

// +build tools

package tools

import (
	_ "github.com/golang/mock/mockgen"
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"
	_ "github.com/goreleaser/godownloader"
	_ "github.com/goreleaser/goreleaser"
	_ "github.com/kamilsk/egg"
	_ "golang.org/x/tools/cmd/goimports"
)

//go:generate go install github.com/golang/mock/mockgen
//go:generate go install github.com/golangci/golangci-lint/cmd/golangci-lint
//go:generate go install github.com/goreleaser/godownloader
//go:generate go install github.com/goreleaser/goreleaser
//go:generate go install github.com/kamilsk/egg
//go:generate go install golang.org/x/tools/cmd/goimports
