// Code generated by github.com/kamilsk/egg. DO NOT EDIT.

// +build tools

package tools

import (
	_ "github.com/golang/mock/mockgen"
	_ "github.com/goreleaser/godownloader"
	_ "golang.org/x/exp/cmd/gorelease"
)

//go:generate go install github.com/golang/mock/mockgen
//go:generate go install github.com/goreleaser/godownloader
//go:generate go install golang.org/x/exp/cmd/gorelease
